package com.actsone.extjsdemo.model;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Subject generated by hbm2java
 */
@Entity
@Table(name = "subject")
public class Subject implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2619528342166889014L;
	private Integer id;
	private String name;
	private String description;
	private Integer numberOfClass;

	public Subject() {
	}

	public Subject(String name, String description, Integer numberOfClass) {
		this.name = name;
		this.description = description;
		this.numberOfClass = numberOfClass;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "NUMBER_OF_CLASS")
	public Integer getNumberOfClass() {
		return this.numberOfClass;
	}

	public void setNumberOfClass(Integer numberOfClass) {
		this.numberOfClass = numberOfClass;
	}

}
