package com.actsone.extjsdemo.sdo;

// Generated Sep 11, 2012 3:28:38 PM by Hibernate Tools 3.4.0.CR1

/**
 * Course generated by hbm2java
 */
public class CourseSDO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1644677632396977605L;
	private Integer id;
	private String name;
	private String description;

	public CourseSDO() {
	}

	public CourseSDO(String name, String description) {
		this.name = name;
		this.description = description;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
