package com.actsone.extjsdemo.sdo;

// Generated Sep 11, 2012 3:28:38 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.codehaus.jackson.annotate.JsonAutoDetect;
import org.codehaus.jackson.map.annotate.JsonDeserialize;
import org.codehaus.jackson.map.annotate.JsonSerialize;

import com.actsone.extjsdemo.util.JsonDateDeserializer;
import com.actsone.extjsdemo.util.JsonDateSerializer;

/**
 * Student generated by hbm2java
 */
@JsonAutoDetect
public class StudentSDO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6778939654660834469L;
	private Integer id;
	private String name;
	private String surName;
	private String phoneNumber;

	private Date birthday;
	private List<ScoreSDO> scores = new ArrayList<ScoreSDO>(0);

	public StudentSDO() {
	}

	public StudentSDO(String name, String surName, String phoneNumber,
			Date birthday, List<ScoreSDO> scores) {
		this.name = name;
		this.surName = surName;
		this.phoneNumber = phoneNumber;
		this.birthday = birthday;
		this.scores = scores;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurName() {
		return this.surName;
	}

	public void setSurName(String surName) {
		this.surName = surName;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@JsonSerialize(using = JsonDateSerializer.class)
	public Date getBirthday() {
		return this.birthday;
	}
	@JsonDeserialize(as = Date.class, using = JsonDateDeserializer.class)
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public List<ScoreSDO> getScores() {
		return this.scores;
	}

	public void setScores(List<ScoreSDO> scores) {
		this.scores = scores;
	}

}
