package com.actsone.extjsdemo.sdo;


/**
 * Subject generated by hbm2java
 */
public class SubjectSDO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2619528342166889014L;
	private Integer id;
	private String name;
	private String description;
	private Integer numberOfClass;

	public SubjectSDO() {
	}

	public SubjectSDO(String name, String description, Integer numberOfClass) {
		this.name = name;
		this.description = description;
		this.numberOfClass = numberOfClass;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getNumberOfClass() {
		return this.numberOfClass;
	}

	public void setNumberOfClass(Integer numberOfClass) {
		this.numberOfClass = numberOfClass;
	}

}
